name: leap_co2_v1
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=12.0.0
  - asttokens=2.2.1
  - attrs=22.1.0
  - aws-c-auth=0.6.27
  - aws-c-cal=0.5.26
  - aws-c-common=0.8.19
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.20
  - aws-c-http=0.7.7
  - aws-c-io=0.13.21
  - aws-c-mqtt=0.8.11
  - aws-c-s3=0.3.0
  - aws-c-sdkutils=0.1.9
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.20.1
  - aws-sdk-cpp=1.10.57
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.4
  - bokeh=3.1.1
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - cartopy=0.21.1
  - cdsapi=0.6.1
  - certifi=2023.5.7
  - cf_xarray=0.8.1
  - cffi=1.15.1
  - cftime=1.6.2
  - charset-normalizer=3.1.0
  - click=8.1.3
  - cloudpickle=2.2.1
  - cmocean=3.0.3
  - colorama=0.4.6
  - colorspacious=1.1.2
  - comm=0.1.3
  - contourpy=1.0.7
  - cryptography=40.0.2
  - curl=8.1.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.5.0
  - dask-core=2023.5.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.5.0
  - entrypoints=0.4
  - esmf=8.4.2
  - esmpy=8.4.2
  - executing=1.2.0
  - fonttools=4.39.4
  - freetype=2.12.1
  - fsspec=2023.5.0
  - geos=3.11.2
  - gettext=0.21.1
  - gflags=2.2.2
  - glib=2.76.2
  - glib-tools=2.76.2
  - glog=0.6.0
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - hdf4=4.2.15
  - hdf5=1.14.0
  - icc_rt=2022.1.0
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - intel-openmp=2021.4.0
  - ipykernel=6.23.1
  - ipython=8.13.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.1.1
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.2.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230125.0
  - libaec=1.0.6
  - libarrow=12.0.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=16.0.3
  - libclang13=16.0.3
  - libcrc32c=1.1.2
  - libcurl=8.1.0
  - libdeflate=1.18
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libglib=2.76.2
  - libgoogle-cloud=2.10.0
  - libgrpc=1.54.2
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libllvm14=14.0.6
  - libnetcdf=4.9.2
  - libogg=1.3.4
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libthrift=0.18.1
  - libtiff=4.5.0
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxgboost=1.7.4
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvmlite=0.40.0
  - locket=1.0.0
  - lxml=4.9.2
  - lz4=4.3.2
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - msgpack-python=1.0.5
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - netcdf-fortran=4.6.0
  - netcdf4=1.6.3
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - numba=0.57.0
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.5.0
  - openssl=3.1.1
  - orc=1.8.3
  - packaging=23.1
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.4.0
  - pcre2=10.40
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.1.2
  - platformdirs=3.5.1
  - ply=3.11
  - pooch=1.7.0
  - proj=9.2.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - py-xgboost=1.7.4
  - pyarrow=12.0.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pyproj=3.5.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.11
  - pytz=2021.3
  - pywin32=304
  - pywinpty=2.0.10
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.8
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - re2=2023.02.02
  - requests=2.29.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - send2trash=1.8.0
  - setuptools=67.7.2
  - shapely=2.0.1
  - sip=6.7.9
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.4
  - sparse=0.14.0
  - sqlite=3.42.0
  - stack_data=0.6.2
  - tbb=2021.9.0
  - tblib=1.7.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - urllib3=1.26.15
  - vc=14.3
  - vc14_runtime=14.34.31931
  - vs2015_runtime=14.34.31931
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.40.0
  - widgetsnbextension=4.0.5
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xarray=0.20.1
  - xesmf=0.7.1
  - xgboost=1.7.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.5.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=3.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2

